# Generated by Django 5.2.12 on 2026-05-09 04:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluxo_oficina', '0002_carro'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdemServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao_ordem', models.TextField(verbose_name='Descrição da Ordem')),
                ('valor_servico', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor do Serviço')),
                ('status', models.CharField(choices=[('aberta', 'Aberta'), ('finalizada', 'Finalizada'), ('cancelada', 'Cancelada')], default='aberta', max_length=20)),
                ('data_entrada_carro', models.DateField(verbose_name='Data de Entrada do Carro')),
                ('data_inicio_servico', models.DateField(blank=True, null=True, verbose_name='Data de Início do Serviço')),
                ('data_fim_servico', models.DateField(blank=True, null=True, verbose_name='Data de Fim do Serviço')),
                ('data_retirada_veiculo', models.DateField(blank=True, null=True, verbose_name='Data de Retirada do Veículo')),
                ('carro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordens', to='fluxo_oficina.carro')),
            ],
            options={
                'verbose_name': 'Ordem de Serviço',
                'verbose_name_plural': 'Ordens de Serviço',
            },
        ),
    ]
